<?php
$TradeInFactory = $block->getTradeInFactory();
$TradeInAddressFactory = $block->getTradeInAddressFactory();
$TradeInAddressShipping = $block->getTradeInAddressShipping()->getData();
$TradeInItemFactory = $block->getTradeInItemFactory();
$id = $block->getId();
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Trade-In Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                        <?php if ($id['trade_in_id']): ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('First Name')) ?></th>
                                <td><?=  /* @noEscape */ $TradeInFactory['firstname'] ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Last Name')) ?></th>
                                <td><?= /* @noEscape */  $TradeInFactory['lastname'] ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Email')) ?></th>
                                <td><?= /* @noEscape */  $TradeInFactory['email'] ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Phone Number')) ?></th>
                                <td><?= /* @noEscape */  $TradeInFactory['phone_number'] ?></td>
                            </tr>
                        <?php endif; ?>
                </table>
            </div>
        </div> 
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Address Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php if ($id['trade_in_id']): ?>
            <div class="admin__page-section-item order-billing-address">
                <?php /* Billing Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Billing Address')) ?></span>
                </div>
                <address class="admin__page-section-item-content">
                    <?= /* @noEscape */ $TradeInAddressFactory['street'].'<br>'.$TradeInAddressFactory['city'].
                        ', '.$TradeInAddressFactory['postcode'].'<br>'.$TradeInAddressFactory['region'] ?>
                </address>
            </div>
            <?php if ($TradeInAddressShipping): ?>
                <div class="admin__page-section-item order-shipping-address">
                    <?php /* Shipping Address */ ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    </div>
                    <address class="admin__page-section-item-content">
                        <?= /* @noEscape */ $TradeInAddressShipping['street'].'<br>'.
                                                $TradeInAddressShipping['city'].', '.
                                                $TradeInAddressShipping['postcode'].'<br>'.
                                                $TradeInAddressShipping['region']
                        ?>
                    </address>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Ordered')) ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table" id="my-orders-table">
            <thead>
                <tr class="headings">
                    <th scope="col" class="col-product-name"><?= $block->escapeHtml(__('Product Name')) ?></th></n>
                    <th scope="col" class="col-price"><?= $block->escapeHtml(__('Price')) ?></th>
                    <th scope="col" class="col-qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                    <th scope="col" class="col-condition"><?= $block->escapeHtml(__('Condition')) ?></th>
                    <th scope="col" class="col-subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
                </tr>
            </thead>
            <tbody class="even">
                    <?php if ($id['trade_in_id']): ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col product_name">
                                <?= /* @noEscape */ $TradeInItemFactory['product_name'] ?>
                            </td>
                            <?php $price = /* @noEscape */ $TradeInItemFactory['price'] ?>
                            <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col price">
                                <?= /* @noEscape */ $block->getFormattedPrice($price);?>
                            </td> 
                            <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                                <?= /* @noEscape */ $TradeInItemFactory['qty'] ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Condition')) ?>" class="col condition">
                                <?= /* @noEscape */ $TradeInItemFactory['condition'] ?>
                            </td>
                            <?php $SubTotal = /* @noEscape */ $TradeInItemFactory['subtotal'] ?>
                            <td data-th="<?= $block->escapeHtml(__('Subtotal')) ?>" class="col subtotal">
                            <?= /* @noEscape */ $block->getFormattedPrice($SubTotal);?>
                            </td>
                        </tr>
                    <?php endif; ?>
            </tbody>
        </table>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Total')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="data-table admin__table-secondary order-subtotal-table">
                        <?php if ($id['trade_in_id']): ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('SubTotal')) ?></th>
                                <?php $OrderSubTotal = /* @noEscape */ $TradeInItemFactory['subtotal'] ?>
                                <td><?= /* @noEscape */ $block->getFormattedPrice($OrderSubTotal);?></td>
                            </tr>
                            <tr class="col-0">
                                <td class="label"><strong><?= $block->escapeHtml(__('Grand Total')) ?></strong></td>
                                <?php $GrandTotal = /* @noEscape */ $TradeInFactory['grand_total'] ?>
                                <td><strong><?= /* @noEscape */ $block->getFormattedPrice($GrandTotal); ?></strong>
                                </td>
                            </tr>
                        <?php endif; ?>
                </table>
            </div>
        </div>
    </div>
</section>