<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Pivotal\TradeIn\Block\TradeInForm $block */
/** @var \Pivotal\TradeIn\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<div class="trade-in-form-wrapper">
    <form class="form trade-in-form"
        action="<?= $block->escapeUrl($block->getFormAction()) ?>"
        id="trade-in-form"
        method="post"
        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        data-mage-init='{"validation":{}}'
        style="width:100%;">

        <div class="tradein-form-steps">
            <div class="step-getin-touch step-title mb-20" data-role="collapsible">
                <div class="step-getin-touch" data-role="trigger">
                    <h2>Get in touch</h2>
                </div>
            </div>
            <div class="step-get-quote step-title mb-20" data-role="collapsible">
                <div class="step-getin-touch" data-role="trigger">
                    <h2>Get quote</h2>
                </div>
            </div>
            <div class="step-arrange-shipping step-title mb-20" data-role="collapsible">
                <div class="step-getin-touch" data-role="trigger">
                    <h2>Arrange shipping</h2>
                </div>
            </div>
            <div class="step-getin-touch-content" data-role="content">
                <div class="main-title">
                    <h1>GET AN INSTANT QUOTE</h1>
                </div>
                <?= $block->getChildHtml('tradeIn.form.addItems') ?>
                <fieldset class="fieldset">
                    <legend class="legend"><span><?= $block->escapeHtml(__('Your details')) ?></span></legend><br />
                    <div class="field note no-label">
                        <?= $block->escapeHtml(__("We need to capture some details from you so we can send across your quote.")) ?>
                    </div>
                    <div class="field firstname required">
                        <label class="label" for="trade-in-firstname"><span><?= $block->escapeHtml(__('Firstname')) ?></span></label>
                        <div class="control">
                            <input name="firstname"
                                id="trade-in-firstname"
                                title="<?= $block->escapeHtmlAttr(__('Firstname')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserFirstName()) ?>"
                                class="input-text"
                                type="text"
                                data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="field lastname required">
                        <label class="label" for="trade-in-lastname"><span><?= $block->escapeHtml(__('Lastname')) ?></span></label>
                        <div class="control">
                            <input name="lastname"
                                id="trade-in-lastname"
                                title="<?= $block->escapeHtmlAttr(__('Lastname')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserLastName()) ?>"
                                class="input-text"
                                type="text"
                                data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="field email required">
                        <label class="label" for="trade-in-email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input name="email"
                                id="trade-in-email"
                                title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                                class="input-text"
                                type="email"
                                data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                    </div>
                    <div class="field phonenumber required">
                        <label class="label" for="trade-in-phonenumber"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                        <div class="control">
                            <input name="phonenumber"
                                id="trade-in-phonenumber"
                                title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                                value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                                class="input-text"
                                type="tel"
                                data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="button" title="<?= $block->escapeHtmlAttr(__('Get quote')) ?>" class="get-quote-btn action primary">
                                <span><?= $block->escapeHtml(__('Get quote')) ?></span>
                            </button>
                        </div>
                    </div>
                </fieldset>
                
            </div>
            <div class="step-get-quote-content" data-role="content">
                <div class="trade-in-quote-items"></div>
            </div>
            <div class="step-arrange-shipping-content" data-role="content">
                <?= $block->getChildHtml('tradeIn.arrange.shipping')?>
                <div class="actions-toolbar" style="display: none;">
                    <div class="primary">
                        <input type="hidden" name="hideit" id="hideit" value="" />
                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                            <span><?= $block->escapeHtml(__('Submit')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/x-magento-init">
    {
        ".trade-in-form-wrapper": {
            "tradeInFormWidget": {}
        }
    }
</script>

<style>
    form.trade-in-form .control {width: 50%;}
    .product-search-item-data {
        border: 1px solid;
        margin-bottom: 5px;
        padding: 10px;
    }
    .add-more-item{text-align: center;}
    .add-more-btn,
    .step-get-quote-content,
    .step-arrange-shipping-content,
    .book-free-shipping-content,
    .book-in-store-drop-off-content,
    .customer-home-address,
    .customer-different-address,
    .home-address-form,
    .different-to-home-address-form {display: none;}
    .tradein-form-steps .step-title {
        display: inline-block;
        text-align: center;
        width: 33%;
    }
    .mb-20 {margin-bottom: 20px;}
    .mt-20 {margin-top: 20px;}
    .error {
        color: #e02b27;
        font-size: 1.2rem;
        margin-top: 7px;
    }
    .main-title {
        text-align: center;
    }
    /* Step 2 */
    tr.item-info {border-top: 1px solid #cccccc;}
    .tradein-form-steps .step-title[aria-selected="true"] h2 {font-weight: bold;}
    .input-group.input-group-qty {max-width: 100px;}
    .qty-wrap {float: left;}
    input.input-group-item-qty {
        padding: 30.5px 0;
        text-align: center;
        max-width: 60px;
        border-right: none;
    }
    .inc-dec-btns {
        float: left;
        display: grid;
    }
    button.inc-dec-btn {
        border-radius: unset;
        background: none;
    }
    button.item-qty-decrease.inc-dec-btn {
        border-top: none;
    }
    /* Step3 */
    .arrange-shipping-wrap .arrange-shipping-title {
        display: inline-block;
        text-align: center;
        width: 49.5%;
    }
    .arrange-shipping-wrap .arrange-shipping-title button,
    .arrange-shipping-wrap .arrange-shipping-title button:hover{
        padding: 15px;
        font-size: 15px;
        color: #ffffff;
        background: #799393;
        border-color: #799393;
    }
    .arrange-shipping-wrap .arrange-shipping-title[aria-selected="true"] button {
        font-weight: bold;
        background-color: #218888;
        border-color: #218888;
        color: #ffffff;
    }
    form.trade-in-form .nested .control {width: 100%;}
</style>